services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ask\AskBatchImporter\:
    resource: '../Classes/*'

  Ask\AskBatchImporter\Fetcher\ProductSourceInterface:
    # ProductSourceInterface: Local file for Testing
    alias: Ask\AskBatchImporter\Fetcher\JsonFileSource
    # ProductSourceInterface: Microsoft Business Central
    # alias: Ask\AskBatchImporter\Fetcher\BcApiClient

  Ask\AskBatchImporter\Fetcher\Dto\BcConnectionConfig:
    factory: [ '@Ask\AskBatchImporter\Fetcher\Dto\BcConnectionConfigProvider', 'create' ]