services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ask\AskBatchImporter\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Fetcher/Dto/BcConnectionConfig.php'
      - '../Classes/Config/ProjectConfig.php'
      - '../Classes/Writer/Typo3Writer.php'
      - '../Classes/Writer/OxidWriter.php'
      - '../Classes/Fetcher/JsonFileSource.php'
      - '../Classes/Fetcher/CsvFileSource.php'